In [40]:
import numpy as np

In [41]:
from sklearn.datasets import load_iris

In [42]:
iris=load_iris()

In [43]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [44]:
print(iris.data)
x=iris.data

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [45]:
y=iris.target
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Pre-processing the dataset

In [46]:
from keras.utils import to_categorical

since there are three data in the output, we have to categorize by one hunt coding


In [47]:
y=to_categorical(y)
print(y)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

splitting the dataset

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)
print(x_train)

[[5.7 2.9 4.2 1.3]
 [7.6 3.  6.6 2.1]
 [5.6 3.  4.5 1.5]
 [5.1 3.5 1.4 0.2]
 [7.7 2.8 6.7 2. ]
 [5.8 2.7 4.1 1. ]
 [5.2 3.4 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.1 3.8 1.9 0.4]
 [5.  2.  3.5 1. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.1 3.3 1.7 0.5]
 [5.6 2.7 4.2 1.3]
 [5.1 3.4 1.5 0.2]
 [5.7 3.  4.2 1.2]
 [7.7 3.8 6.7 2.2]
 [4.6 3.2 1.4 0.2]
 [6.2 2.9 4.3 1.3]
 [5.7 2.5 5.  2. ]
 [5.5 4.2 1.4 0.2]
 [6.  3.  4.8 1.8]
 [5.8 2.7 5.1 1.9]
 [6.  2.2 4.  1. ]
 [5.4 3.  4.5 1.5]
 [6.2 3.4 5.4 2.3]
 [5.5 2.3 4.  1.3]
 [5.4 3.9 1.7 0.4]
 [5.  2.3 3.3 1. ]
 [6.4 2.7 5.3 1.9]
 [5.  3.3 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 2.4 3.8 1.1]
 [6.7 3.  5.  1.7]
 [4.9 3.1 1.5 0.2]
 [5.8 2.8 5.1 2.4]
 [5.  3.4 1.5 0.2]
 [5.  3.5 1.6 0.6]
 [5.9 3.2 4.8 1.8]
 [5.1 2.5 3.  1.1]
 [6.9 3.2 5.7 2.3]
 [6.  2.7 5.1 1.6]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [5.5 2.5 4.  1.3]
 [4.4 2.9 1.4 0.2]
 [4.3 3.  1.1 0.1]
 [6.  2.2 5.  1.5]
 [7.2 3.2 6.  1.8]
 [4.6 3.1 1.5 0.2]
 [5.1 3.5 1.4 0.3]
 [4.4 3.  1.

## Standardizing the data:
Standardization just means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.

In [50]:
from sklearn.preprocessing import MinMaxScaler

In [51]:
scaler_object=MinMaxScaler()

In [52]:
print(x_train)
scaler_object.fit(x_train)

[[5.7 2.9 4.2 1.3]
 [7.6 3.  6.6 2.1]
 [5.6 3.  4.5 1.5]
 [5.1 3.5 1.4 0.2]
 [7.7 2.8 6.7 2. ]
 [5.8 2.7 4.1 1. ]
 [5.2 3.4 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.1 3.8 1.9 0.4]
 [5.  2.  3.5 1. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.1 3.3 1.7 0.5]
 [5.6 2.7 4.2 1.3]
 [5.1 3.4 1.5 0.2]
 [5.7 3.  4.2 1.2]
 [7.7 3.8 6.7 2.2]
 [4.6 3.2 1.4 0.2]
 [6.2 2.9 4.3 1.3]
 [5.7 2.5 5.  2. ]
 [5.5 4.2 1.4 0.2]
 [6.  3.  4.8 1.8]
 [5.8 2.7 5.1 1.9]
 [6.  2.2 4.  1. ]
 [5.4 3.  4.5 1.5]
 [6.2 3.4 5.4 2.3]
 [5.5 2.3 4.  1.3]
 [5.4 3.9 1.7 0.4]
 [5.  2.3 3.3 1. ]
 [6.4 2.7 5.3 1.9]
 [5.  3.3 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 2.4 3.8 1.1]
 [6.7 3.  5.  1.7]
 [4.9 3.1 1.5 0.2]
 [5.8 2.8 5.1 2.4]
 [5.  3.4 1.5 0.2]
 [5.  3.5 1.6 0.6]
 [5.9 3.2 4.8 1.8]
 [5.1 2.5 3.  1.1]
 [6.9 3.2 5.7 2.3]
 [6.  2.7 5.1 1.6]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [5.5 2.5 4.  1.3]
 [4.4 2.9 1.4 0.2]
 [4.3 3.  1.1 0.1]
 [6.  2.2 5.  1.5]
 [7.2 3.2 6.  1.8]
 [4.6 3.1 1.5 0.2]
 [5.1 3.5 1.4 0.3]
 [4.4 3.  1.

MinMaxScaler()

In [53]:

scaled_x_train=scaler_object.transform(x_train)
print(scaled_x_train)

[[0.41176471 0.40909091 0.55357143 0.5       ]
 [0.97058824 0.45454545 0.98214286 0.83333333]
 [0.38235294 0.45454545 0.60714286 0.58333333]
 [0.23529412 0.68181818 0.05357143 0.04166667]
 [1.         0.36363636 1.         0.79166667]
 [0.44117647 0.31818182 0.53571429 0.375     ]
 [0.26470588 0.63636364 0.05357143 0.04166667]
 [0.20588235 0.68181818 0.03571429 0.08333333]
 [0.23529412 0.81818182 0.14285714 0.125     ]
 [0.20588235 0.         0.42857143 0.375     ]
 [0.58823529 0.31818182 0.67857143 0.70833333]
 [0.14705882 0.63636364 0.14285714 0.04166667]
 [0.20588235 0.45454545 0.08928571 0.04166667]
 [0.23529412 0.59090909 0.10714286 0.16666667]
 [0.38235294 0.31818182 0.55357143 0.5       ]
 [0.23529412 0.63636364 0.07142857 0.04166667]
 [0.41176471 0.45454545 0.55357143 0.45833333]
 [1.         0.81818182 1.         0.875     ]
 [0.08823529 0.54545455 0.05357143 0.04166667]
 [0.55882353 0.40909091 0.57142857 0.5       ]
 [0.41176471 0.22727273 0.69642857 0.79166667]
 [0.35294118 

In [54]:
scaled_x_test=scaler_object.transform(x_test)
print(scaled_x_test)

[[ 0.52941176  0.36363636  0.64285714  0.45833333]
 [ 0.41176471  0.81818182  0.10714286  0.08333333]
 [ 1.          0.27272727  1.03571429  0.91666667]
 [ 0.5         0.40909091  0.60714286  0.58333333]
 [ 0.73529412  0.36363636  0.66071429  0.54166667]
 [ 0.32352941  0.63636364  0.07142857  0.125     ]
 [ 0.38235294  0.40909091  0.44642857  0.5       ]
 [ 0.76470588  0.5         0.71428571  0.91666667]
 [ 0.55882353  0.09090909  0.60714286  0.58333333]
 [ 0.44117647  0.31818182  0.5         0.45833333]
 [ 0.64705882  0.54545455  0.71428571  0.79166667]
 [ 0.14705882  0.45454545  0.05357143  0.        ]
 [ 0.35294118  0.68181818  0.03571429  0.04166667]
 [ 0.17647059  0.5         0.07142857  0.        ]
 [ 0.23529412  0.81818182  0.07142857  0.08333333]
 [ 0.58823529  0.59090909  0.64285714  0.625     ]
 [ 0.64705882  0.45454545  0.83928571  0.875     ]
 [ 0.38235294  0.22727273  0.5         0.41666667]
 [ 0.41176471  0.36363636  0.60714286  0.5       ]
 [ 0.61764706  0.36363636  0.80

In [55]:
scaled_x_train.max()

1.0

## Building the neural network with Keras


In [56]:
from keras.models import Sequential
from keras.layers import Dense

In [57]:
model=Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))#Input Layer
model.add(Dense(8,input_dim=4,activation='relu'))#Hidden layer
model.add(Dense(3,activation='softmax'))#Output Layer
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [58]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 8)                 40        
                                                                 
 dense_7 (Dense)             (None, 8)                 72        
                                                                 
 dense_8 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139 (556.00 Byte)
Trainable params: 139 (556.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


##Train the model

In [59]:
model.fit(scaled_x_train,y_train,epochs=150,verbose=2)

Epoch 1/150


4/4 - 1s - loss: 1.1223 - accuracy: 0.3100 - 763ms/epoch - 191ms/step
Epoch 2/150
4/4 - 0s - loss: 1.1148 - accuracy: 0.3200 - 15ms/epoch - 4ms/step
Epoch 3/150
4/4 - 0s - loss: 1.1080 - accuracy: 0.3200 - 12ms/epoch - 3ms/step
Epoch 4/150
4/4 - 0s - loss: 1.1017 - accuracy: 0.3500 - 12ms/epoch - 3ms/step
Epoch 5/150
4/4 - 0s - loss: 1.0960 - accuracy: 0.3600 - 13ms/epoch - 3ms/step
Epoch 6/150
4/4 - 0s - loss: 1.0902 - accuracy: 0.3700 - 10ms/epoch - 3ms/step
Epoch 7/150
4/4 - 0s - loss: 1.0845 - accuracy: 0.3700 - 11ms/epoch - 3ms/step
Epoch 8/150
4/4 - 0s - loss: 1.0786 - accuracy: 0.3800 - 9ms/epoch - 2ms/step
Epoch 9/150
4/4 - 0s - loss: 1.0725 - accuracy: 0.4100 - 11ms/epoch - 3ms/step
Epoch 10/150
4/4 - 0s - loss: 1.0664 - accuracy: 0.4400 - 10ms/epoch - 3ms/step
Epoch 11/150
4/4 - 0s - loss: 1.0602 - accuracy: 0.4700 - 8ms/epoch - 2ms/step
Epoch 12/150
4/4 - 0s - loss: 1.0539 - accuracy: 0.5300 - 7ms/epoch - 2ms/step
Epoch 13/150
4/4 - 0s - loss: 1.0476 - accuracy: 0.5700 - 10m

## PREDICTING THE ACCURACY

In [60]:
y_pred_prob=model.predict(scaled_x_test)
print(y_pred)


2/2 [==============================] - 0s 4ms/step
[2 1 2 2 2 1 2 2 2 2 2 1 1 1 1 2 2 2 2 2 1 2 1 2 2 2 2 2 1 1 1 1 2 1 1 2 2
 1 1 1 2 2 2 1 1 2 2 2 2 2]


Previous cell returned the probabilites, however we need the one hunted coding data

In [61]:
# y_pred=model.predict_classes(scaled_x_test)
y_pred = np.argmax(y_pred_prob, axis=1)
print(y_pred)

[1 0 2 1 2 0 1 2 2 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0 1 2 2 1 2]


In [62]:
print(np.argmax(y_test,axis=1))

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0 1 2 2 1 2]


In [63]:
pred=model.predict_classes(scaled_x_test)

AttributeError: 'Sequential' object has no attribute 'predict_classes'

In [66]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test.argmax(axis=1),y_pred))
print(accuracy_score(y_test.argmax(axis=1),y_pred))

[[19  0  0]
 [ 0 13  2]
 [ 0  0 16]]
0.96
