## Process text 
## Clear text
## tokenize the text and create sequences with keras

In [3]:
def read_file(filepath):
    with open(filepath) as f:
        str_text=f.read()
    return str_text


In [4]:
read_file("moby_dick_four_chapters.txt")

'Call me Ishmael.  Some years ago--never mind how long\nprecisely--having little or no money in my purse, and nothing\nparticular to interest me on shore, I thought I would sail about a\nlittle and see the watery part of the world.  It is a way I have of\ndriving off the spleen and regulating the circulation.  Whenever I\nfind myself growing grim about the mouth; whenever it is a damp,\ndrizzly November in my soul; whenever I find myself involuntarily\npausing before coffin warehouses, and bringing up the rear of every\nfuneral I meet; and especially whenever my hypos get such an upper\nhand of me, that it requires a strong moral principle to prevent me\nfrom deliberately stepping into the street, and methodically knocking\npeople\'s hats off--then, I account it high time to get to sea as soon\nas I can.  This is my substitute for pistol and ball.  With a\nphilosophical flourish Cato throws himself upon his sword; I quietly\ntake to the ship.  There is nothing surprising in this.  If t

In [5]:
import spacy


In [10]:
nlp=spacy.load('en_core_web_sm',disable=['parser','tagger','ner'])
# nlp = spacy.load('en',disable=['parser', 'tagger','ner'])


nlp.max_length=1198623

c:\Users\nandi.LAPTOP-6NVS0PRF\AppData\Local\Programs\Python\Python311\Lib\site-packages\spacy\util.py:910: UserWarning: [W095] Model 'en_core_web_sm' (3.6.0) was trained with spaCy v3.6.0 and may not be 100% compatible with the current version (3.7.1). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)


Removing extra unwanted string from text

In [12]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if( token.text) not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [14]:
d=read_file('moby_dick_four_chapters.txt')
tokens=separate_punc(d)

c:\Users\nandi.LAPTOP-6NVS0PRF\AppData\Local\Programs\Python\Python311\Lib\site-packages\spacy\pipeline\lemmatizer.py:211: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)


# 25 words -> predict the 26th word

In [33]:
train_len=25+1
text_sequences=[]

for i in range(train_len,len(tokens)):
    seq=tokens[i-train_len:i]
    text_sequences.append(seq)
print((text_sequences[0]))

['call', 'me', 'ishmael', 'some', 'years', 'ago', 'never', 'mind', 'how', 'long', 'precisely', 'having', 'little', 'or', 'no', 'money', 'in', 'my', 'purse', 'and', 'nothing', 'particular', 'to', 'interest', 'me', 'on']


# Keras Tokenization

In [26]:
from keras.preprocessing.text import Tokenizer

tokenizer=Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences=tokenizer.texts_to_sequences(text_sequences)


In [31]:
print((sequences[0]))

[956, 14, 263, 51, 261, 408, 87, 219, 129, 111, 954, 260, 50, 43, 38, 314, 7, 23, 546, 3, 150, 259, 6, 2713, 14, 24]


In [32]:
print(tokenizer.index_word)#common words with index number

{1: 'the', 2: 'a', 3: 'and', 4: 'of', 5: 'i', 6: 'to', 7: 'in', 8: 'it', 9: 'that', 10: 'he', 11: 'his', 12: 'was', 13: 'but', 14: 'me', 15: 'with', 16: 'as', 17: 'at', 18: 'this', 19: 'you', 20: 'is', 21: 'all', 22: 'for', 23: 'my', 24: 'on', 25: 'be', 26: "'s", 27: 'not', 28: 'from', 29: 'there', 30: 'one', 31: 'up', 32: 'what', 33: 'him', 34: 'so', 35: 'bed', 36: 'now', 37: 'about', 38: 'no', 39: 'into', 40: 'by', 41: 'were', 42: 'out', 43: 'or', 44: 'harpooneer', 45: 'had', 46: 'then', 47: 'have', 48: 'an', 49: 'upon', 50: 'little', 51: 'some', 52: 'old', 53: 'like', 54: 'if', 55: 'they', 56: 'would', 57: 'do', 58: 'over', 59: 'landlord', 60: 'thought', 61: 'room', 62: 'when', 63: 'could', 64: "n't", 65: 'night', 66: 'here', 67: 'head', 68: 'such', 69: 'which', 70: 'man', 71: 'did', 72: 'sea', 73: 'time', 74: 'other', 75: 'very', 76: 'go', 77: 'these', 78: 'more', 79: 'though', 80: 'first', 81: 'sort', 82: 'said', 83: 'last', 84: 'down', 85: 'most', 86: 'been', 87: 'never', 88: 'yo

In [35]:
print(tokenizer.word_counts)#words with their repetitions

OrderedDict([('call', 27), ('me', 2471), ('ishmael', 133), ('some', 758), ('years', 135), ('ago', 84), ('never', 449), ('mind', 164), ('how', 321), ('long', 374), ('precisely', 37), ('having', 142), ('little', 767), ('or', 950), ('no', 1003), ('money', 120), ('in', 5647), ('my', 1786), ('purse', 71), ('and', 9646), ('nothing', 281), ('particular', 152), ('to', 6497), ('interest', 24), ('on', 1716), ('shore', 26), ('i', 7150), ('thought', 676), ('would', 702), ('sail', 104), ('about', 1014), ('a', 10377), ('see', 416), ('the', 15540), ('watery', 26), ('part', 234), ('of', 8287), ('world', 234), ('it', 4238), ('is', 1950), ('way', 390), ('have', 806), ('driving', 26), ('off', 416), ('spleen', 26), ('regulating', 26), ('circulation', 26), ('whenever', 130), ('find', 78), ('myself', 416), ('growing', 26), ('grim', 26), ('mouth', 130), ('damp', 78), ('drizzly', 26), ('november', 26), ('soul', 78), ('involuntarily', 52), ('pausing', 52), ('before', 364), ('coffin', 104), ('warehouses', 52), 

In [37]:
vocabulary_size=len(tokenizer.word_counts)#total unique words


changing squences into numpy array

In [38]:
import numpy as np

In [39]:
sequences=np.array(sequences)


In [40]:
print(sequences)

[[ 956   14  263 ... 2713   14   24]
 [  14  263   51 ...   14   24  957]
 [ 263   51  261 ...   24  957    5]
 ...
 [ 952   12  166 ...  262   53    2]
 [  12  166 2712 ...   53    2 2718]
 [ 166 2712    3 ...    2 2718   26]]


## Creating our LSTM based model

In [42]:
import keras 
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [43]:
print(sequences[:,:-1])

[[ 956   14  263 ...    6 2713   14]
 [  14  263   51 ... 2713   14   24]
 [ 263   51  261 ...   14   24  957]
 ...
 [ 952   12  166 ...   11  262   53]
 [  12  166 2712 ...  262   53    2]
 [ 166 2712    3 ...   53    2 2718]]


In [44]:
print(sequences[:,-1])

[  24  957    5 ...    2 2718   26]


In [53]:
x=sequences[:,:-1]
print(x)

[[ 956   14  263 ...    6 2713   14]
 [  14  263   51 ... 2713   14   24]
 [ 263   51  261 ...   14   24  957]
 ...
 [ 952   12  166 ...   11  262   53]
 [  12  166 2712 ...  262   53    2]
 [ 166 2712    3 ...   53    2 2718]]


In [48]:
from keras.utils import to_categorical
y=sequences[:,-1]
# One hunt encoding
y=to_categorical(y,num_classes=vocabulary_size+1)
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]


In [52]:
print(sequences[:,-1])
print(y.shape)

[  24  957    5 ...    2 2718   26]
(11312, 2719)


In [55]:
seq_len=x.shape[1]
print(vocabulary_size)

2718


In [56]:
def create_model(vocabulary_size,seq_len):
    model=Sequential()
    model.add(Embedding(vocabulary_size,15,input_length=seq_len))
    model.add(LSTM(150,return_sequences=True))
    model.add(LSTM(150))
    model.add(Dense(150,activation='relu'))
    model.add(Dense(vocabulary_size,activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.summary()
    return model

In [57]:
model=create_model(vocabulary_size+1,seq_len)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 25, 15)            40785     
                                                                 
 lstm (LSTM)                 (None, 25, 150)           99600     
                                                                 
 lstm_1 (LSTM)               (None, 150)               180600    
                                                                 
 dense (Dense)               (None, 150)               22650     
                                                                 
 dense_1 (Dense)             (None, 2719)              410569    
                                                                 
Total params: 754204 (2.88 MB)
Trainable params: 754204 (2.88 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [61]:
from pickle import dump,load

In [62]:
model.fit(x,y,batch_size=128,epochs=2,verbose=1)

Epoch 1/2
89/89 [==============================] - 22s 194ms/step - loss: 6.8601 - accuracy: 0.0470
Epoch 2/2
89/89 [==============================] - 18s 203ms/step - loss: 6.3868 - accuracy: 0.0529


In [63]:
model.save('result.h5')

c:\Users\nandi.LAPTOP-6NVS0PRF\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


# generating new text


In [ ]:
from random import randint
from pickle import load
from keras.models import load_model
# from keras